api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    graphql:
        enabled: true
        graphiql: true
    swagger:
        versions: [3]
