version: '3'

services:
  php-fpm:
    container_name: php_dev
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./../:/var/www/
    environment:
      - APP_ENV=dev
    ports:
      - '8000:8000'
