version: '3'

services:
  mysql:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
#  nginx:
#    container_name: nginx
#    image: nginx:stable-alpine
#    ports:
#      - '8080:80'
#    volumes:
#      - ./app:/var/www/symfony_docker
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php-fpm
#      - mysql
  php-fpm:
    container_name: php_dev
#    depends_on:
#      - mysql
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./../:/var/www/
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://sf_user:sf_password@mysql:3306/sf_dev?serverVersion=8.0
    ports:
      - '8000:8000'
